### Save a new product
POST http://localhost:8000/posts/create-post
Content-Type: application/json

{
  "title": "Sample Product",
  "content": "This is a sample product description.",
  "userId": "657a6aaf-e249-4888-80ba-ebf4ab376183"
}

### Get all products
GET http://localhost:8000/posts/get-posts

### Save a new user
POST http://localhost:8000/users
Content-Type: application/json

{
  "name": "John Doe",
  "age": 30,
  "email": "john@example.com"
}

### Get all users
GET http://localhost:8000/users
