### Create a user
POST http://localhost:8000/users
Content-Type: application/json

{
  "name": "Abhra Doe",
  "age": 30,
  "email": "abhra@example.com"
}

### Get all users
GET http://localhost:8000/users

### Create a post
POST http://localhost:8000/posts
Content-Type: application/json

{
  "title": "Sample Product",
  "content": "This is a sample product description.",
  "userId": "657a6aaf-e249-4888-80ba-ebf4ab376183"
}

### Get all posts
GET http://localhost:8000/posts
